// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msgScheme.proto

package msgScheme;

public final class MsgScheme {
  private MsgScheme() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .AMsg.Head head = 1;</code>
     */
    int getHeadValue();
    /**
     * <code>optional .AMsg.Head head = 1;</code>
     */
    MsgScheme.AMsg.Head getHead();

    /**
     * <code>optional .LoginRequest loginRequest = 2;</code>
     */
    MsgScheme.LoginRequest getLoginRequest();
    /**
     * <code>optional .LoginRequest loginRequest = 2;</code>
     */
    MsgScheme.LoginRequestOrBuilder getLoginRequestOrBuilder();

    /**
     * <code>optional .LoginResponse loginResponse = 3;</code>
     */
    MsgScheme.LoginResponse getLoginResponse();
    /**
     * <code>optional .LoginResponse loginResponse = 3;</code>
     */
    MsgScheme.LoginResponseOrBuilder getLoginResponseOrBuilder();

    public MsgScheme.AMsg.BodyCase getBodyCase();
  }
  /**
   * Protobuf type {@code AMsg}
   */
  public  static final class AMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:AMsg)
      AMsgOrBuilder {
    // Use AMsg.newBuilder() to construct.
    private AMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AMsg() {
      head_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private AMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              head_ = rawValue;
              break;
            }
            case 18: {
              MsgScheme.LoginRequest.Builder subBuilder = null;
              if (bodyCase_ == 2) {
                subBuilder = ((MsgScheme.LoginRequest) body_).toBuilder();
              }
              body_ =
                  input.readMessage(MsgScheme.LoginRequest.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((MsgScheme.LoginRequest) body_);
                body_ = subBuilder.buildPartial();
              }
              bodyCase_ = 2;
              break;
            }
            case 26: {
              MsgScheme.LoginResponse.Builder subBuilder = null;
              if (bodyCase_ == 3) {
                subBuilder = ((MsgScheme.LoginResponse) body_).toBuilder();
              }
              body_ =
                  input.readMessage(MsgScheme.LoginResponse.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((MsgScheme.LoginResponse) body_);
                body_ = subBuilder.buildPartial();
              }
              bodyCase_ = 3;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MsgScheme.internal_static_AMsg_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MsgScheme.internal_static_AMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MsgScheme.AMsg.class, MsgScheme.AMsg.Builder.class);
    }

    /**
     * Protobuf enum {@code AMsg.Head}
     */
    public enum Head
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>First_Msg = 0;</code>
       */
      First_Msg(0),
      /**
       * <code>Login_Request = 100001;</code>
       */
      Login_Request(100001),
      /**
       * <code>Login_Response = 100002;</code>
       */
      Login_Response(100002),
      /**
       * <code>CreateRoom_Request = 100003;</code>
       */
      CreateRoom_Request(100003),
      /**
       * <code>CreateRoom_Response = 100004;</code>
       */
      CreateRoom_Response(100004),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>First_Msg = 0;</code>
       */
      public static final int First_Msg_VALUE = 0;
      /**
       * <code>Login_Request = 100001;</code>
       */
      public static final int Login_Request_VALUE = 100001;
      /**
       * <code>Login_Response = 100002;</code>
       */
      public static final int Login_Response_VALUE = 100002;
      /**
       * <code>CreateRoom_Request = 100003;</code>
       */
      public static final int CreateRoom_Request_VALUE = 100003;
      /**
       * <code>CreateRoom_Response = 100004;</code>
       */
      public static final int CreateRoom_Response_VALUE = 100004;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static Head valueOf(int value) {
        return forNumber(value);
      }

      public static Head forNumber(int value) {
        switch (value) {
          case 0: return First_Msg;
          case 100001: return Login_Request;
          case 100002: return Login_Response;
          case 100003: return CreateRoom_Request;
          case 100004: return CreateRoom_Response;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Head>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Head> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Head>() {
              public Head findValueByNumber(int number) {
                return Head.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return MsgScheme.AMsg.getDescriptor().getEnumTypes().get(0);
      }

      private static final Head[] VALUES = values();

      public static Head valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Head(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:AMsg.Head)
    }

    private int bodyCase_ = 0;
    private Object body_;
    public enum BodyCase
        implements com.google.protobuf.Internal.EnumLite {
      LOGINREQUEST(2),
      LOGINRESPONSE(3),
      BODY_NOT_SET(0);
      private final int value;
      private BodyCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static BodyCase valueOf(int value) {
        return forNumber(value);
      }

      public static BodyCase forNumber(int value) {
        switch (value) {
          case 2: return LOGINREQUEST;
          case 3: return LOGINRESPONSE;
          case 0: return BODY_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public BodyCase
    getBodyCase() {
      return BodyCase.forNumber(
          bodyCase_);
    }

    public static final int HEAD_FIELD_NUMBER = 1;
    private int head_;
    /**
     * <code>optional .AMsg.Head head = 1;</code>
     */
    public int getHeadValue() {
      return head_;
    }
    /**
     * <code>optional .AMsg.Head head = 1;</code>
     */
    public MsgScheme.AMsg.Head getHead() {
      MsgScheme.AMsg.Head result = MsgScheme.AMsg.Head.valueOf(head_);
      return result == null ? MsgScheme.AMsg.Head.UNRECOGNIZED : result;
    }

    public static final int LOGINREQUEST_FIELD_NUMBER = 2;
    /**
     * <code>optional .LoginRequest loginRequest = 2;</code>
     */
    public MsgScheme.LoginRequest getLoginRequest() {
      if (bodyCase_ == 2) {
         return (MsgScheme.LoginRequest) body_;
      }
      return MsgScheme.LoginRequest.getDefaultInstance();
    }
    /**
     * <code>optional .LoginRequest loginRequest = 2;</code>
     */
    public MsgScheme.LoginRequestOrBuilder getLoginRequestOrBuilder() {
      if (bodyCase_ == 2) {
         return (MsgScheme.LoginRequest) body_;
      }
      return MsgScheme.LoginRequest.getDefaultInstance();
    }

    public static final int LOGINRESPONSE_FIELD_NUMBER = 3;
    /**
     * <code>optional .LoginResponse loginResponse = 3;</code>
     */
    public MsgScheme.LoginResponse getLoginResponse() {
      if (bodyCase_ == 3) {
         return (MsgScheme.LoginResponse) body_;
      }
      return MsgScheme.LoginResponse.getDefaultInstance();
    }
    /**
     * <code>optional .LoginResponse loginResponse = 3;</code>
     */
    public MsgScheme.LoginResponseOrBuilder getLoginResponseOrBuilder() {
      if (bodyCase_ == 3) {
         return (MsgScheme.LoginResponse) body_;
      }
      return MsgScheme.LoginResponse.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (head_ != MsgScheme.AMsg.Head.First_Msg.getNumber()) {
        output.writeEnum(1, head_);
      }
      if (bodyCase_ == 2) {
        output.writeMessage(2, (MsgScheme.LoginRequest) body_);
      }
      if (bodyCase_ == 3) {
        output.writeMessage(3, (MsgScheme.LoginResponse) body_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (head_ != MsgScheme.AMsg.Head.First_Msg.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, head_);
      }
      if (bodyCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (MsgScheme.LoginRequest) body_);
      }
      if (bodyCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (MsgScheme.LoginResponse) body_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MsgScheme.AMsg)) {
        return super.equals(obj);
      }
      MsgScheme.AMsg other = (MsgScheme.AMsg) obj;

      boolean result = true;
      result = result && head_ == other.head_;
      result = result && getBodyCase().equals(
          other.getBodyCase());
      if (!result) return false;
      switch (bodyCase_) {
        case 2:
          result = result && getLoginRequest()
              .equals(other.getLoginRequest());
          break;
        case 3:
          result = result && getLoginResponse()
              .equals(other.getLoginResponse());
          break;
        case 0:
        default:
      }
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + HEAD_FIELD_NUMBER;
      hash = (53 * hash) + head_;
      switch (bodyCase_) {
        case 2:
          hash = (37 * hash) + LOGINREQUEST_FIELD_NUMBER;
          hash = (53 * hash) + getLoginRequest().hashCode();
          break;
        case 3:
          hash = (37 * hash) + LOGINRESPONSE_FIELD_NUMBER;
          hash = (53 * hash) + getLoginResponse().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MsgScheme.AMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MsgScheme.AMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MsgScheme.AMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MsgScheme.AMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MsgScheme.AMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MsgScheme.AMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static MsgScheme.AMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static MsgScheme.AMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MsgScheme.AMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MsgScheme.AMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MsgScheme.AMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AMsg)
        MsgScheme.AMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MsgScheme.internal_static_AMsg_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MsgScheme.internal_static_AMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MsgScheme.AMsg.class, MsgScheme.AMsg.Builder.class);
      }

      // Construct using msgScheme.MsgScheme.AMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        head_ = 0;

        bodyCase_ = 0;
        body_ = null;
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MsgScheme.internal_static_AMsg_descriptor;
      }

      public MsgScheme.AMsg getDefaultInstanceForType() {
        return MsgScheme.AMsg.getDefaultInstance();
      }

      public MsgScheme.AMsg build() {
        MsgScheme.AMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public MsgScheme.AMsg buildPartial() {
        MsgScheme.AMsg result = new MsgScheme.AMsg(this);
        result.head_ = head_;
        if (bodyCase_ == 2) {
          if (loginRequestBuilder_ == null) {
            result.body_ = body_;
          } else {
            result.body_ = loginRequestBuilder_.build();
          }
        }
        if (bodyCase_ == 3) {
          if (loginResponseBuilder_ == null) {
            result.body_ = body_;
          } else {
            result.body_ = loginResponseBuilder_.build();
          }
        }
        result.bodyCase_ = bodyCase_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MsgScheme.AMsg) {
          return mergeFrom((MsgScheme.AMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MsgScheme.AMsg other) {
        if (other == MsgScheme.AMsg.getDefaultInstance()) return this;
        if (other.head_ != 0) {
          setHeadValue(other.getHeadValue());
        }
        switch (other.getBodyCase()) {
          case LOGINREQUEST: {
            mergeLoginRequest(other.getLoginRequest());
            break;
          }
          case LOGINRESPONSE: {
            mergeLoginResponse(other.getLoginResponse());
            break;
          }
          case BODY_NOT_SET: {
            break;
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MsgScheme.AMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MsgScheme.AMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bodyCase_ = 0;
      private Object body_;
      public BodyCase
          getBodyCase() {
        return BodyCase.forNumber(
            bodyCase_);
      }

      public Builder clearBody() {
        bodyCase_ = 0;
        body_ = null;
        onChanged();
        return this;
      }


      private int head_ = 0;
      /**
       * <code>optional .AMsg.Head head = 1;</code>
       */
      public int getHeadValue() {
        return head_;
      }
      /**
       * <code>optional .AMsg.Head head = 1;</code>
       */
      public Builder setHeadValue(int value) {
        head_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .AMsg.Head head = 1;</code>
       */
      public MsgScheme.AMsg.Head getHead() {
        MsgScheme.AMsg.Head result = MsgScheme.AMsg.Head.valueOf(head_);
        return result == null ? MsgScheme.AMsg.Head.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .AMsg.Head head = 1;</code>
       */
      public Builder setHead(MsgScheme.AMsg.Head value) {
        if (value == null) {
          throw new NullPointerException();
        }

        head_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .AMsg.Head head = 1;</code>
       */
      public Builder clearHead() {

        head_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          LoginRequest, LoginRequest.Builder, LoginRequestOrBuilder> loginRequestBuilder_;
      /**
       * <code>optional .LoginRequest loginRequest = 2;</code>
       */
      public MsgScheme.LoginRequest getLoginRequest() {
        if (loginRequestBuilder_ == null) {
          if (bodyCase_ == 2) {
            return (MsgScheme.LoginRequest) body_;
          }
          return MsgScheme.LoginRequest.getDefaultInstance();
        } else {
          if (bodyCase_ == 2) {
            return loginRequestBuilder_.getMessage();
          }
          return MsgScheme.LoginRequest.getDefaultInstance();
        }
      }
      /**
       * <code>optional .LoginRequest loginRequest = 2;</code>
       */
      public Builder setLoginRequest(MsgScheme.LoginRequest value) {
        if (loginRequestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          body_ = value;
          onChanged();
        } else {
          loginRequestBuilder_.setMessage(value);
        }
        bodyCase_ = 2;
        return this;
      }
      /**
       * <code>optional .LoginRequest loginRequest = 2;</code>
       */
      public Builder setLoginRequest(
          MsgScheme.LoginRequest.Builder builderForValue) {
        if (loginRequestBuilder_ == null) {
          body_ = builderForValue.build();
          onChanged();
        } else {
          loginRequestBuilder_.setMessage(builderForValue.build());
        }
        bodyCase_ = 2;
        return this;
      }
      /**
       * <code>optional .LoginRequest loginRequest = 2;</code>
       */
      public Builder mergeLoginRequest(MsgScheme.LoginRequest value) {
        if (loginRequestBuilder_ == null) {
          if (bodyCase_ == 2 &&
              body_ != MsgScheme.LoginRequest.getDefaultInstance()) {
            body_ = MsgScheme.LoginRequest.newBuilder((MsgScheme.LoginRequest) body_)
                .mergeFrom(value).buildPartial();
          } else {
            body_ = value;
          }
          onChanged();
        } else {
          if (bodyCase_ == 2) {
            loginRequestBuilder_.mergeFrom(value);
          }
          loginRequestBuilder_.setMessage(value);
        }
        bodyCase_ = 2;
        return this;
      }
      /**
       * <code>optional .LoginRequest loginRequest = 2;</code>
       */
      public Builder clearLoginRequest() {
        if (loginRequestBuilder_ == null) {
          if (bodyCase_ == 2) {
            bodyCase_ = 0;
            body_ = null;
            onChanged();
          }
        } else {
          if (bodyCase_ == 2) {
            bodyCase_ = 0;
            body_ = null;
          }
          loginRequestBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .LoginRequest loginRequest = 2;</code>
       */
      public MsgScheme.LoginRequest.Builder getLoginRequestBuilder() {
        return getLoginRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .LoginRequest loginRequest = 2;</code>
       */
      public MsgScheme.LoginRequestOrBuilder getLoginRequestOrBuilder() {
        if ((bodyCase_ == 2) && (loginRequestBuilder_ != null)) {
          return loginRequestBuilder_.getMessageOrBuilder();
        } else {
          if (bodyCase_ == 2) {
            return (MsgScheme.LoginRequest) body_;
          }
          return MsgScheme.LoginRequest.getDefaultInstance();
        }
      }
      /**
       * <code>optional .LoginRequest loginRequest = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          LoginRequest, LoginRequest.Builder, LoginRequestOrBuilder>
          getLoginRequestFieldBuilder() {
        if (loginRequestBuilder_ == null) {
          if (!(bodyCase_ == 2)) {
            body_ = MsgScheme.LoginRequest.getDefaultInstance();
          }
          loginRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              LoginRequest, LoginRequest.Builder, LoginRequestOrBuilder>(
                  (MsgScheme.LoginRequest) body_,
                  getParentForChildren(),
                  isClean());
          body_ = null;
        }
        bodyCase_ = 2;
        onChanged();;
        return loginRequestBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          LoginResponse, LoginResponse.Builder, LoginResponseOrBuilder> loginResponseBuilder_;
      /**
       * <code>optional .LoginResponse loginResponse = 3;</code>
       */
      public MsgScheme.LoginResponse getLoginResponse() {
        if (loginResponseBuilder_ == null) {
          if (bodyCase_ == 3) {
            return (MsgScheme.LoginResponse) body_;
          }
          return MsgScheme.LoginResponse.getDefaultInstance();
        } else {
          if (bodyCase_ == 3) {
            return loginResponseBuilder_.getMessage();
          }
          return MsgScheme.LoginResponse.getDefaultInstance();
        }
      }
      /**
       * <code>optional .LoginResponse loginResponse = 3;</code>
       */
      public Builder setLoginResponse(MsgScheme.LoginResponse value) {
        if (loginResponseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          body_ = value;
          onChanged();
        } else {
          loginResponseBuilder_.setMessage(value);
        }
        bodyCase_ = 3;
        return this;
      }
      /**
       * <code>optional .LoginResponse loginResponse = 3;</code>
       */
      public Builder setLoginResponse(
          MsgScheme.LoginResponse.Builder builderForValue) {
        if (loginResponseBuilder_ == null) {
          body_ = builderForValue.build();
          onChanged();
        } else {
          loginResponseBuilder_.setMessage(builderForValue.build());
        }
        bodyCase_ = 3;
        return this;
      }
      /**
       * <code>optional .LoginResponse loginResponse = 3;</code>
       */
      public Builder mergeLoginResponse(MsgScheme.LoginResponse value) {
        if (loginResponseBuilder_ == null) {
          if (bodyCase_ == 3 &&
              body_ != MsgScheme.LoginResponse.getDefaultInstance()) {
            body_ = MsgScheme.LoginResponse.newBuilder((MsgScheme.LoginResponse) body_)
                .mergeFrom(value).buildPartial();
          } else {
            body_ = value;
          }
          onChanged();
        } else {
          if (bodyCase_ == 3) {
            loginResponseBuilder_.mergeFrom(value);
          }
          loginResponseBuilder_.setMessage(value);
        }
        bodyCase_ = 3;
        return this;
      }
      /**
       * <code>optional .LoginResponse loginResponse = 3;</code>
       */
      public Builder clearLoginResponse() {
        if (loginResponseBuilder_ == null) {
          if (bodyCase_ == 3) {
            bodyCase_ = 0;
            body_ = null;
            onChanged();
          }
        } else {
          if (bodyCase_ == 3) {
            bodyCase_ = 0;
            body_ = null;
          }
          loginResponseBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .LoginResponse loginResponse = 3;</code>
       */
      public MsgScheme.LoginResponse.Builder getLoginResponseBuilder() {
        return getLoginResponseFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .LoginResponse loginResponse = 3;</code>
       */
      public MsgScheme.LoginResponseOrBuilder getLoginResponseOrBuilder() {
        if ((bodyCase_ == 3) && (loginResponseBuilder_ != null)) {
          return loginResponseBuilder_.getMessageOrBuilder();
        } else {
          if (bodyCase_ == 3) {
            return (MsgScheme.LoginResponse) body_;
          }
          return MsgScheme.LoginResponse.getDefaultInstance();
        }
      }
      /**
       * <code>optional .LoginResponse loginResponse = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          LoginResponse, LoginResponse.Builder, LoginResponseOrBuilder>
          getLoginResponseFieldBuilder() {
        if (loginResponseBuilder_ == null) {
          if (!(bodyCase_ == 3)) {
            body_ = MsgScheme.LoginResponse.getDefaultInstance();
          }
          loginResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              LoginResponse, LoginResponse.Builder, LoginResponseOrBuilder>(
                  (MsgScheme.LoginResponse) body_,
                  getParentForChildren(),
                  isClean());
          body_ = null;
        }
        bodyCase_ = 3;
        onChanged();;
        return loginResponseBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:AMsg)
    }

    // @@protoc_insertion_point(class_scope:AMsg)
    private static final MsgScheme.AMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MsgScheme.AMsg();
    }

    public static MsgScheme.AMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AMsg>
        PARSER = new com.google.protobuf.AbstractParser<AMsg>() {
      public AMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new AMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AMsg> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<AMsg> getParserForType() {
      return PARSER;
    }

    public MsgScheme.AMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LoginRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LoginRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string userId = 1;</code>
     */
    String getUserId();
    /**
     * <code>optional string userId = 1;</code>
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    /**
     * <code>optional string password = 2;</code>
     */
    String getPassword();
    /**
     * <code>optional string password = 2;</code>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();
  }
  /**
   * <pre>
   *100001
   * </pre>
   *
   * Protobuf type {@code LoginRequest}
   */
  public  static final class LoginRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:LoginRequest)
      LoginRequestOrBuilder {
    // Use LoginRequest.newBuilder() to construct.
    private LoginRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LoginRequest() {
      userId_ = "";
      password_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private LoginRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              userId_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              password_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MsgScheme.internal_static_LoginRequest_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MsgScheme.internal_static_LoginRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MsgScheme.LoginRequest.class, MsgScheme.LoginRequest.Builder.class);
    }

    public static final int USERID_FIELD_NUMBER = 1;
    private volatile Object userId_;
    /**
     * <code>optional string userId = 1;</code>
     */
    public String getUserId() {
      Object ref = userId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string userId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASSWORD_FIELD_NUMBER = 2;
    private volatile Object password_;
    /**
     * <code>optional string password = 2;</code>
     */
    public String getPassword() {
      Object ref = password_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        password_ = s;
        return s;
      }
    }
    /**
     * <code>optional string password = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      Object ref = password_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUserIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userId_);
      }
      if (!getPasswordBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, password_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUserIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userId_);
      }
      if (!getPasswordBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, password_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MsgScheme.LoginRequest)) {
        return super.equals(obj);
      }
      MsgScheme.LoginRequest other = (MsgScheme.LoginRequest) obj;

      boolean result = true;
      result = result && getUserId()
          .equals(other.getUserId());
      result = result && getPassword()
          .equals(other.getPassword());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId().hashCode();
      hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
      hash = (53 * hash) + getPassword().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MsgScheme.LoginRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MsgScheme.LoginRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MsgScheme.LoginRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MsgScheme.LoginRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MsgScheme.LoginRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MsgScheme.LoginRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static MsgScheme.LoginRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static MsgScheme.LoginRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MsgScheme.LoginRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MsgScheme.LoginRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MsgScheme.LoginRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *100001
     * </pre>
     *
     * Protobuf type {@code LoginRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LoginRequest)
        MsgScheme.LoginRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MsgScheme.internal_static_LoginRequest_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MsgScheme.internal_static_LoginRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MsgScheme.LoginRequest.class, MsgScheme.LoginRequest.Builder.class);
      }

      // Construct using msgScheme.MsgScheme.LoginRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        userId_ = "";

        password_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MsgScheme.internal_static_LoginRequest_descriptor;
      }

      public MsgScheme.LoginRequest getDefaultInstanceForType() {
        return MsgScheme.LoginRequest.getDefaultInstance();
      }

      public MsgScheme.LoginRequest build() {
        MsgScheme.LoginRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public MsgScheme.LoginRequest buildPartial() {
        MsgScheme.LoginRequest result = new MsgScheme.LoginRequest(this);
        result.userId_ = userId_;
        result.password_ = password_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MsgScheme.LoginRequest) {
          return mergeFrom((MsgScheme.LoginRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MsgScheme.LoginRequest other) {
        if (other == MsgScheme.LoginRequest.getDefaultInstance()) return this;
        if (!other.getUserId().isEmpty()) {
          userId_ = other.userId_;
          onChanged();
        }
        if (!other.getPassword().isEmpty()) {
          password_ = other.password_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MsgScheme.LoginRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MsgScheme.LoginRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object userId_ = "";
      /**
       * <code>optional string userId = 1;</code>
       */
      public String getUserId() {
        Object ref = userId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string userId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string userId = 1;</code>
       */
      public Builder setUserId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string userId = 1;</code>
       */
      public Builder clearUserId() {

        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string userId = 1;</code>
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        userId_ = value;
        onChanged();
        return this;
      }

      private Object password_ = "";
      /**
       * <code>optional string password = 2;</code>
       */
      public String getPassword() {
        Object ref = password_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string password = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string password = 2;</code>
       */
      public Builder setPassword(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string password = 2;</code>
       */
      public Builder clearPassword() {

        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>optional string password = 2;</code>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        password_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:LoginRequest)
    }

    // @@protoc_insertion_point(class_scope:LoginRequest)
    private static final MsgScheme.LoginRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MsgScheme.LoginRequest();
    }

    public static MsgScheme.LoginRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LoginRequest>
        PARSER = new com.google.protobuf.AbstractParser<LoginRequest>() {
      public LoginRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new LoginRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LoginRequest> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<LoginRequest> getParserForType() {
      return PARSER;
    }

    public MsgScheme.LoginRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LoginResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LoginResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bool ok = 1;</code>
     */
    boolean getOk();
  }
  /**
   * <pre>
   *100002
   * </pre>
   *
   * Protobuf type {@code LoginResponse}
   */
  public  static final class LoginResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:LoginResponse)
      LoginResponseOrBuilder {
    // Use LoginResponse.newBuilder() to construct.
    private LoginResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LoginResponse() {
      ok_ = false;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private LoginResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              ok_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MsgScheme.internal_static_LoginResponse_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MsgScheme.internal_static_LoginResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MsgScheme.LoginResponse.class, MsgScheme.LoginResponse.Builder.class);
    }

    public static final int OK_FIELD_NUMBER = 1;
    private boolean ok_;
    /**
     * <code>optional bool ok = 1;</code>
     */
    public boolean getOk() {
      return ok_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (ok_ != false) {
        output.writeBool(1, ok_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (ok_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, ok_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MsgScheme.LoginResponse)) {
        return super.equals(obj);
      }
      MsgScheme.LoginResponse other = (MsgScheme.LoginResponse) obj;

      boolean result = true;
      result = result && (getOk()
          == other.getOk());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + OK_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getOk());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MsgScheme.LoginResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MsgScheme.LoginResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MsgScheme.LoginResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MsgScheme.LoginResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MsgScheme.LoginResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MsgScheme.LoginResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static MsgScheme.LoginResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static MsgScheme.LoginResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MsgScheme.LoginResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MsgScheme.LoginResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MsgScheme.LoginResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *100002
     * </pre>
     *
     * Protobuf type {@code LoginResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LoginResponse)
        MsgScheme.LoginResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MsgScheme.internal_static_LoginResponse_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MsgScheme.internal_static_LoginResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MsgScheme.LoginResponse.class, MsgScheme.LoginResponse.Builder.class);
      }

      // Construct using msgScheme.MsgScheme.LoginResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        ok_ = false;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MsgScheme.internal_static_LoginResponse_descriptor;
      }

      public MsgScheme.LoginResponse getDefaultInstanceForType() {
        return MsgScheme.LoginResponse.getDefaultInstance();
      }

      public MsgScheme.LoginResponse build() {
        MsgScheme.LoginResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public MsgScheme.LoginResponse buildPartial() {
        MsgScheme.LoginResponse result = new MsgScheme.LoginResponse(this);
        result.ok_ = ok_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MsgScheme.LoginResponse) {
          return mergeFrom((MsgScheme.LoginResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MsgScheme.LoginResponse other) {
        if (other == MsgScheme.LoginResponse.getDefaultInstance()) return this;
        if (other.getOk() != false) {
          setOk(other.getOk());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MsgScheme.LoginResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MsgScheme.LoginResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean ok_ ;
      /**
       * <code>optional bool ok = 1;</code>
       */
      public boolean getOk() {
        return ok_;
      }
      /**
       * <code>optional bool ok = 1;</code>
       */
      public Builder setOk(boolean value) {

        ok_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool ok = 1;</code>
       */
      public Builder clearOk() {

        ok_ = false;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:LoginResponse)
    }

    // @@protoc_insertion_point(class_scope:LoginResponse)
    private static final MsgScheme.LoginResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MsgScheme.LoginResponse();
    }

    public static MsgScheme.LoginResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LoginResponse>
        PARSER = new com.google.protobuf.AbstractParser<LoginResponse>() {
      public LoginResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new LoginResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LoginResponse> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<LoginResponse> getParserForType() {
      return PARSER;
    }

    public MsgScheme.LoginResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AMsg_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AMsg_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LoginRequest_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LoginRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LoginResponse_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LoginResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017msgScheme.proto\"\357\001\n\004AMsg\022\030\n\004head\030\001 \001(\016" +
      "2\n.AMsg.Head\022%\n\014loginRequest\030\002 \001(\0132\r.Log" +
      "inRequestH\000\022\'\n\rloginResponse\030\003 \001(\0132\016.Log" +
      "inResponseH\000\"u\n\004Head\022\r\n\tFirst_Msg\020\000\022\023\n\rL" +
      "ogin_Request\020\241\215\006\022\024\n\016Login_Response\020\242\215\006\022\030" +
      "\n\022CreateRoom_Request\020\243\215\006\022\031\n\023CreateRoom_R" +
      "esponse\020\244\215\006B\006\n\004body\"0\n\014LoginRequest\022\016\n\006u" +
      "serId\030\001 \001(\t\022\020\n\010password\030\002 \001(\t\"\033\n\rLoginRe" +
      "sponse\022\n\n\002ok\030\001 \001(\010B\013\n\tmsgSchemeb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_AMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AMsg_descriptor,
        new String[] { "Head", "LoginRequest", "LoginResponse", "Body", });
    internal_static_LoginRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_LoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LoginRequest_descriptor,
        new String[] { "UserId", "Password", });
    internal_static_LoginResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_LoginResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LoginResponse_descriptor,
        new String[] { "Ok", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
